// GENERATED by packages/tokens/scripts/build-tokens.ts from src/tokens.ts — do not edit by hand.
/** @type {import("tailwindcss").Config} */
const preset = {
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: "var(--cooud-primary)",
          foreground: "var(--cooud-primary-foreground)",
          strong: "var(--cooud-primary-text)",
        },
        accent: {
          DEFAULT: "var(--cooud-accent)",
          foreground: "var(--cooud-accent-foreground)",
        },
        surface: {
          base: "var(--cooud-surface-base)",
          inset: "var(--cooud-surface-inset)",
          raised: "var(--cooud-surface-raised)",
          overlay: "var(--cooud-surface-overlay)",
          elevated: "var(--cooud-surface-elevated)",
          floating: "var(--cooud-surface-floating)",
        },
        fg: {
          DEFAULT: "var(--cooud-fg)",
          secondary: "var(--cooud-fg-secondary)",
          tertiary: "var(--cooud-fg-tertiary)",
          muted: "var(--cooud-fg-muted)",
          inverse: "var(--cooud-fg-inverse)",
        },
        border: {
          DEFAULT: "var(--cooud-border)",
          strong: "var(--cooud-border-strong)",
          soft: "var(--cooud-border-soft)",
        },
        ring: "var(--cooud-ring)",
        success: {
          DEFAULT: "var(--cooud-success)",
          strong: "var(--cooud-success-text)",
        },
        warning: {
          DEFAULT: "var(--cooud-warning)",
          strong: "var(--cooud-warning-text)",
        },
        error: {
          DEFAULT: "var(--cooud-error)",
          strong: "var(--cooud-error-text)",
        },
        info: {
          DEFAULT: "var(--cooud-info)",
          strong: "var(--cooud-info-text)",
        },
        chart: {
          1: "var(--cooud-chart-1)",
          2: "var(--cooud-chart-2)",
          3: "var(--cooud-chart-3)",
          4: "var(--cooud-chart-4)",
          5: "var(--cooud-chart-5)",
        },
      },
      borderRadius: {
        sm: "max(0px, calc(var(--cooud-radius) - 8px))",
        md: "max(0px, calc(var(--cooud-radius) - 4px))",
        lg: "var(--cooud-radius)",
        xl: "calc(var(--cooud-radius) + 4px)",
        "2xl": "calc(var(--cooud-radius) + 8px)",
        "3xl": "calc(var(--cooud-radius) + 14px)",
      },
      boxShadow: {
        xs: "var(--cooud-shadow-xs)",
        sm: "var(--cooud-shadow-sm)",
        md: "var(--cooud-shadow-md)",
        lg: "var(--cooud-shadow-lg)",
        glow: "var(--cooud-shadow-glow)",
      },
      fontFamily: {
        sans: "var(--cooud-font-sans)",
        display: "var(--cooud-font-display)",
        mono: "var(--cooud-font-mono)",
      },
      transitionTimingFunction: {
        "out-quart": "cubic-bezier(0.16, 1, 0.3, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
      },
    },
  },
};

export default preset;
