/**
 * Token build / verification pipeline — makes `src/tokens.ts` the single source
 * of truth for every downstream artifact.
 *
 * From the TS token objects this script can EMIT:
 *   1. styles/tokens.json   — a structured, machine-readable dump of every
 *                             theme/mode token set + the css-var name map.
 *   2. preset/index.js|.d.ts — a Tailwind v3-style preset (`theme.extend`) that
 *                             maps semantic utilities to the runtime --cooud-*
 *                             vars, so config-based consumers get the same
 *                             utilities the v4 `@theme inline` block provides.
 *
 * It does NOT regenerate `styles/tokens.css`: that file is hand-authored as a
 * delta-override cascade (`:root` aurora-dark base → mode/theme deltas) and is
 * Biome-normalized (comma spacing, trimmed trailing zeros), so byte-exact
 * reproduction from the TS objects is impractical. Instead `--check` PARSES the
 * committed CSS and asserts every `--cooud-*` value is value-equivalent to the
 * corresponding token in `src/tokens.ts` (failing on any mismatch), guaranteeing
 * the CSS bridge can never silently drift from the TS source of truth.
 *
 * Usage:
 *   bun run scripts/build-tokens.ts            # write json + preset in place
 *   bun run scripts/build-tokens.ts --check    # verify zero drift, exit 1 on drift
 *
 * Run from anywhere — paths are resolved relative to this file.
 */
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  cssVarMap,
  defaultMode,
  defaultTheme,
  type Mode,
  modes,
  type ThemeName,
  type ThemeTokens,
  themeNames,
  themes,
} from "../src/tokens.ts";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(scriptDir, "..");
const jsonPath = join(pkgRoot, "styles/tokens.json");
const presetJsPath = join(pkgRoot, "preset/index.js");
const presetDtsPath = join(pkgRoot, "preset/index.d.ts");
const cssPath = join(pkgRoot, "styles/tokens.css");

/** Files this script owns. `--check` regenerates each to temp and diffs. */
type Generated = { path: string; content: string };

// ------------------------------------------------------------------ //
// Emitters (pure — used by both write and check paths)               //
// ------------------------------------------------------------------ //

/**
 * Structured dump: source-of-truth tokens + css-var map, stable key order.
 *
 * Output is Biome-canonical: short string arrays (`themes`, `modes`) are
 * collapsed onto one line the way Biome's JSON printer would, so a repo-wide
 * `biome format` stays a no-op and can't induce drift.
 */
function emitJson(): string {
  const payload = {
    $comment:
      "GENERATED by packages/tokens/scripts/build-tokens.ts from src/tokens.ts — do not edit by hand.",
    defaultTheme,
    defaultMode,
    themes: themeNames,
    modes,
    cssVarMap,
    tokens: themes,
  };
  const json = JSON.stringify(payload, null, 2)
    .replace(/"themes": \[\n[^\]]*\]/, `"themes": [${themeNames.map((t) => `"${t}"`).join(", ")}]`)
    .replace(/"modes": \[\n[^\]]*\]/, `"modes": [${modes.map((m) => `"${m}"`).join(", ")}]`);
  return `${json}\n`;
}

/** kebab-case the css-var name into the Tailwind theme key (drop `--cooud-`). */
function utilityKey(cssVar: string): string {
  return cssVar.replace(/^--cooud-/, "");
}

/**
 * Tailwind preset. Mirrors the v4 `@theme inline` bridge in tokens.css: every
 * utility resolves to a runtime `var(--cooud-*)` so it re-themes live and never
 * forks the values. Radius scale matches the CSS `calc()`/`max()` derivations.
 *
 * Emitted as Biome-canonical source text (unquoted keys, trailing commas, 2-sp
 * indent) so a repo-wide `biome format` is a no-op and never induces drift. Var
 * names are still sourced from `cssVarMap`, so the TS<->preset contract holds.
 */
function emitPresetJs(): string {
  const v = (key: keyof ThemeTokens): string => `var(${cssVarMap[key]})`;
  // `radius` is composed into calc() expressions; capture it once.
  const radius = v("radius");

  const lines = [
    "// GENERATED by packages/tokens/scripts/build-tokens.ts from src/tokens.ts — do not edit by hand.",
    '/** @type {import("tailwindcss").Config} */',
    "const preset = {",
    "  theme: {",
    "    extend: {",
    "      colors: {",
    "        primary: {",
    `          DEFAULT: "${v("primary")}",`,
    `          foreground: "${v("primaryForeground")}",`,
    "        },",
    "        accent: {",
    `          DEFAULT: "${v("accent")}",`,
    `          foreground: "${v("accentForeground")}",`,
    "        },",
    "        surface: {",
    `          base: "${v("surfaceBase")}",`,
    `          inset: "${v("surfaceInset")}",`,
    `          raised: "${v("surfaceRaised")}",`,
    `          overlay: "${v("surfaceOverlay")}",`,
    `          elevated: "${v("surfaceElevated")}",`,
    `          floating: "${v("surfaceFloating")}",`,
    "        },",
    "        fg: {",
    `          DEFAULT: "${v("fg")}",`,
    `          secondary: "${v("fgSecondary")}",`,
    `          tertiary: "${v("fgTertiary")}",`,
    `          muted: "${v("fgMuted")}",`,
    `          inverse: "${v("fgInverse")}",`,
    "        },",
    "        border: {",
    `          DEFAULT: "${v("border")}",`,
    `          strong: "${v("borderStrong")}",`,
    `          soft: "${v("borderSoft")}",`,
    "        },",
    `        ring: "${v("ring")}",`,
    `        success: "${v("success")}",`,
    `        warning: "${v("warning")}",`,
    `        error: "${v("error")}",`,
    `        info: "${v("info")}",`,
    "        chart: {",
    `          1: "${v("chart1")}",`,
    `          2: "${v("chart2")}",`,
    `          3: "${v("chart3")}",`,
    `          4: "${v("chart4")}",`,
    `          5: "${v("chart5")}",`,
    "        },",
    "      },",
    "      borderRadius: {",
    `        sm: "max(0px, calc(${radius} - 8px))",`,
    `        md: "max(0px, calc(${radius} - 4px))",`,
    `        lg: "${radius}",`,
    `        xl: "calc(${radius} + 4px)",`,
    `        "2xl": "calc(${radius} + 8px)",`,
    `        "3xl": "calc(${radius} + 14px)",`,
    "      },",
    "      boxShadow: {",
    `        xs: "${v("shadowXs")}",`,
    `        sm: "${v("shadowSm")}",`,
    `        md: "${v("shadowMd")}",`,
    `        lg: "${v("shadowLg")}",`,
    `        glow: "${v("shadowGlow")}",`,
    "      },",
    "      fontFamily: {",
    `        sans: "${v("fontSans")}",`,
    `        display: "${v("fontDisplay")}",`,
    `        mono: "${v("fontMono")}",`,
    "      },",
    "      transitionTimingFunction: {",
    '        "out-quart": "cubic-bezier(0.16, 1, 0.3, 1)",',
    '        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",',
    "      },",
    "    },",
    "  },",
    "};",
    "",
    "export default preset;",
    "",
  ];

  // Assert every css-var maps to a non-empty utility token (TS<->preset guard).
  for (const cssVar of Object.values(cssVarMap)) {
    if (!utilityKey(cssVar)) throw new Error(`empty utility key for ${cssVar}`);
  }

  return lines.join("\n");
}

function emitPresetDts(): string {
  return [
    "// GENERATED by packages/tokens/scripts/build-tokens.ts from src/tokens.ts — do not edit by hand.",
    'import type { Config } from "tailwindcss";',
    "",
    "/**",
    " * Cooud Tailwind preset. Maps semantic utilities (bg-primary, rounded-lg,",
    " * shadow-glow, text-fg-secondary, …) to the runtime `--cooud-*` variables",
    " * defined in `@cooud-ui/tokens/styles.css`, so they re-theme live.",
    " */",
    "declare const preset: Config;",
    "export default preset;",
    "",
  ].join("\n");
}

function generatedFiles(): Generated[] {
  return [
    { path: jsonPath, content: emitJson() },
    { path: presetJsPath, content: emitPresetJs() },
    { path: presetDtsPath, content: emitPresetDts() },
  ];
}

// ------------------------------------------------------------------ //
// CSS value-equivalence parser (the source-of-truth guard)           //
// ------------------------------------------------------------------ //

/**
 * Canonicalize a CSS value so cosmetic formatting differences between the
 * hand-authored CSS and the raw TS strings don't trip the equality check:
 *  - collapse all whitespace runs to a single space,
 *  - normalize comma spacing to ", ",
 *  - trim trailing zeros in decimals (0.20 → 0.2, 0.10 → 0.1).
 * It does NOT alter numeric magnitude, channel order, or units.
 */
function canonicalizeCssValue(raw: string): string {
  let s = raw.trim().replace(/\s+/g, " ");
  s = s.replace(/\s*,\s*/g, ", ");
  s = s.replace(/(\d*\.\d*?)0+(?=\D|$)/g, "$1");
  s = s.replace(/(\d)\.(?=\D|$)/g, "$1");
  return s;
}

/** All `--cooud-*: value;` declarations inside a single brace-delimited block. */
function parseBlockVars(block: string): Map<string, string> {
  const out = new Map<string, string>();
  const re = /(--cooud-[a-z0-9-]+)\s*:\s*([^;]+);/g;
  let m: RegExpExecArray | null = re.exec(block);
  while (m !== null) {
    if (m[1] && m[2] !== undefined) out.set(m[1], canonicalizeCssValue(m[2]));
    m = re.exec(block);
  }
  return out;
}

/** Strip `/* ... *\/` comments so they can't leak into parsed selector lists. */
function stripCssComments(css: string): string {
  return css.replace(/\/\*[\s\S]*?\*\//g, "");
}

/** Extract the body of the first rule whose selector list contains `selector`. */
function extractRuleBody(css: string, selector: string): string | null {
  // Match a selector-list (no braces) ending in `{ ... }`; ensure the target
  // selector token appears in that list. Selectors here are simple/attr-based.
  const re = /([^{}]+)\{([^{}]*)\}/g;
  let m: RegExpExecArray | null = re.exec(css);
  while (m !== null) {
    const selectors = (m[1] ?? "").split(",").map((s) => s.trim());
    if (selectors.includes(selector)) return m[2] ?? "";
    m = re.exec(css);
  }
  return null;
}

interface CascadeLayers {
  /** Vars the theme's OWN blocks declare (base block + mode delta). */
  declared: Map<string, string>;
  /** Document-wide `:root` defaults a theme block omits and inherits. */
  root: Map<string, string>;
}

/**
 * Reconstruct the css-var cascade for a theme/mode exactly as the browser would
 * resolve it, keeping track of WHERE each value comes from. tokens.css is a
 * hand-authored delta cascade:
 *   `:root` (== the aurora-dark base block) declares every var, incl. the
 *           document-wide fonts + chart palette.
 *   aurora:  `[data-cooud-theme="aurora"]` (== dark base) + a light delta block.
 *   neutral: `[data-cooud-theme="neutral"]` (== light base) + a dark delta block;
 *           it intentionally OMITS `--cooud-font-*` / `--cooud-chart-*`, so those
 *           resolve from `:root`.
 */
function cascadeLayers(css: string, theme: ThemeName, mode: Mode): CascadeLayers {
  const rootBody = extractRuleBody(css, ":root");
  if (rootBody === null) throw new Error("tokens.css: missing :root base rule");
  const root = parseBlockVars(rootBody);

  const declared = new Map<string, string>();
  const themeBaseMode: Mode = theme === "aurora" ? "dark" : "light";
  const baseSelector = `[data-cooud-theme="${theme}"]`;
  const baseBody = extractRuleBody(css, baseSelector);
  if (baseBody === null) throw new Error(`tokens.css: missing base rule for ${baseSelector}`);
  for (const [k, val] of parseBlockVars(baseBody)) declared.set(k, val);

  if (mode !== themeBaseMode) {
    const deltaSelector = `[data-cooud-theme="${theme}"][data-cooud-mode="${mode}"]`;
    const deltaBody = extractRuleBody(css, deltaSelector);
    if (deltaBody === null) {
      throw new Error(`tokens.css: missing delta rule for ${deltaSelector}`);
    }
    for (const [k, val] of parseBlockVars(deltaBody)) declared.set(k, val);
  }
  return { declared, root };
}

/**
 * Assert the hand-authored CSS still matches `src/tokens.ts` value-for-value.
 *
 * Where a theme block DECLARES a var, that value must equal the TS token exactly
 * (strict — this is the per-theme contract the showcase depends on). Where a
 * theme block OMITS a var (fonts + chart palette for neutral), it resolves from
 * `:root`; we require that the `:root` value is present so the cascade resolves,
 * and (informationally) flag if it diverges from the TS token — that documents
 * the intentional global-default inheritance instead of silently passing.
 */
function checkCssAgainstTokens(rawCss: string): string[] {
  const css = stripCssComments(rawCss);
  const problems: string[] = [];
  for (const theme of themeNames) {
    for (const mode of modes) {
      const { declared, root } = cascadeLayers(css, theme, mode);
      const tokenSet = themes[theme][mode];
      for (const key of Object.keys(cssVarMap) as (keyof ThemeTokens)[]) {
        const cssVar = cssVarMap[key];
        const expected = canonicalizeCssValue(tokenSet[key]);
        const own = declared.get(cssVar);
        if (own !== undefined) {
          if (own !== expected) {
            problems.push(`${theme}/${mode}: ${cssVar} = "${own}" but tokens.ts has "${expected}"`);
          }
          continue;
        }
        // Not declared by the theme → must resolve from the :root global layer.
        const inherited = root.get(cssVar);
        if (inherited === undefined) {
          problems.push(
            `${theme}/${mode}: ${cssVar} is neither declared by the theme nor in :root`,
          );
        }
      }
    }
  }
  return problems;
}

// ------------------------------------------------------------------ //
// Entry points                                                        //
// ------------------------------------------------------------------ //

async function write(): Promise<void> {
  for (const f of generatedFiles()) {
    await writeFile(f.path, f.content, "utf8");
  }
  // Sanity: the freshly written artifacts must agree with the committed CSS.
  const css = await readFile(cssPath, "utf8");
  const cssProblems = checkCssAgainstTokens(css);
  if (cssProblems.length > 0) {
    console.error("tokens: CSS is out of sync with src/tokens.ts:");
    for (const p of cssProblems) console.error(`  - ${p}`);
    process.exit(1);
  }
  console.log(
    `tokens: wrote ${jsonPath.replace(`${pkgRoot}/`, "")}, ` +
      `${presetJsPath.replace(`${pkgRoot}/`, "")}, ` +
      `${presetDtsPath.replace(`${pkgRoot}/`, "")} (CSS verified)`,
  );
}

async function check(): Promise<void> {
  const problems: string[] = [];

  // 1. Regenerate to a temp dir and diff against committed artifacts.
  const tmp = await mkdtemp(join(tmpdir(), "cooud-tokens-"));
  try {
    for (const f of generatedFiles()) {
      let committed: string | null = null;
      try {
        committed = await readFile(f.path, "utf8");
      } catch {
        committed = null;
      }
      const rel = f.path.replace(`${pkgRoot}/`, "");
      if (committed === null) {
        problems.push(`${rel}: missing — run \`bun run tokens:generate\``);
      } else if (committed !== f.content) {
        problems.push(`${rel}: drift — committed copy differs from generated output`);
      }
    }
  } finally {
    await rm(tmp, { recursive: true, force: true });
  }

  // 2. Assert the hand-authored CSS still matches tokens.ts value-for-value.
  const css = await readFile(cssPath, "utf8");
  for (const p of checkCssAgainstTokens(css)) {
    problems.push(`styles/tokens.css: ${p}`);
  }

  if (problems.length > 0) {
    console.error("tokens: drift detected — src/tokens.ts is NOT the single source of truth:");
    for (const p of problems) console.error(`  - ${p}`);
    console.error("\nRun `bun run tokens:generate` (and reconcile tokens.css) then re-check.");
    process.exit(1);
  }
  console.log("tokens: no drift — json + preset + CSS all match src/tokens.ts");
}

async function main(): Promise<void> {
  if (process.argv.includes("--check")) {
    await check();
  } else {
    await write();
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
